### ISSUE TITLE
Print Bug - No Content Shown Above 992px Breakpoint

### ISSUE THREAD

**Issue by jayde** [openam/bootstrap-responsive-tabs#13]
When I try to print a page with the responsive tabs, if my screen size is larger than 992px the content disappears. But if it is smaller than 992px then the content appears.

![image](https://cloud.githubusercontent.com/assets/1153971/3680716/7e014c30-12b1-11e4-95a9-4b936540bb64.png)

**Comment by openam** [comment]
It still won't be visible if we start with accordions, and move content to tabs. When you view it on a desktop it'll move it from the accordions to the tabs, and then when it prints it'll try to use the mobile view, because the print page is narrower than the desktop, but the javascript won't run at that time.

**Comment by andrea-spotsoftware** [comment]
same issue, any idea to fix it?
